[package]
name = "randomman"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.8", features = ["derive"] }
common = { path = "../../common" }
itertools = "0.13.0"
num-bigint = "0.4.6"
rayon = "1.10.0"
