[workspace]
resolver = "2"
members = [
  "backend_rs",
  "common",
  "communicate",
  "oka",
  "printer",
  "sandbox/hello",
  "sandbox/lifegame-wasm",
  "sandbox/lifegame",
  "tanakh/solver", "chun/spaceship_order",
]
