[package]
name = "scmcomp"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
argopt = "0.3.0"
common = { path = "../common" }
reqwest = { version = "0.12", default-features = false, features = [
    "blocking",
    "rustls-tls",
] }
