[package]
name = "icfpc2024"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "icfpc2024"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
common = { path = "../common" }
