[package]
name = "lifegame-wasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
lifegame = { path = "../lifegame" }
wasm-bindgen = "0.2"
