"""empty message

Revision ID: 4dd46eebd83c
Revises: d8bb476ea5ce
Create Date: 2024-06-28 17:00:30.825907

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4dd46eebd83c'
down_revision = 'd8bb476ea5ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scoreboardlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('total_score_row', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lambdaman_score_row', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('spaceship_score_row', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('threed_score_row', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('efficiency_score_row', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scoreparseresultlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('score_parse_result', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scoreparseresultlog')
    op.drop_table('scoreboardlog')
    # ### end Alembic commands ###
