"""empty message

Revision ID: 9f50696e400c
Revises: 09fbd809b8a2
Create Date: 2024-06-28 12:19:17.145862

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9f50696e400c'
down_revision = '09fbd809b8a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_communicationlog_decoded_request'), 'communicationlog', ['decoded_request'], unique=False)
    op.create_index('ix_communicationlog_decoded_request_id', 'communicationlog', ['decoded_request', sa.text('id DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_communicationlog_decoded_request_id', table_name='communicationlog')
    op.drop_index(op.f('ix_communicationlog_decoded_request'), table_name='communicationlog')
    # ### end Alembic commands ###
