"""empty message

Revision ID: d8bb476ea5ce
Revises: 09fbd809b8a2
Create Date: 2024-06-28 12:29:45.369857

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd8bb476ea5ce'
down_revision = '09fbd809b8a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communicationlog', sa.Column('decoded_request_prefix', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_communicationlog_decoded_request_prefix'), 'communicationlog', ['decoded_request_prefix'], unique=False)
    op.create_index('ix_communicationlog_decoded_request_prefix_id', 'communicationlog', ['decoded_request_prefix', sa.text('id DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_communicationlog_decoded_request_prefix_id', table_name='communicationlog')
    op.drop_index(op.f('ix_communicationlog_decoded_request_prefix'), table_name='communicationlog')
    op.drop_column('communicationlog', 'decoded_request_prefix')
    # ### end Alembic commands ###
