[package]
name = "compressor"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
common = { path = "../../common" }
itertools = "0.13.0"
num-bigint = "0.4.6"
