services:
  db:
    image: postgres:16
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

  redis:
    image: redis:7
    restart: always
    volumes:
      - redis-data:/data
    ports:
      - "127.0.0.1:6379:6379"

volumes:
  postgres-data:
  redis-data:
