[package]
name = "generator"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.44"
env_logger = "0.11.3"
log = "0.4.22"
num-bigint = "0.4.6"
argopt = "0.3.0"
common = { path = "../../common" }
