name: frontend_deploy

on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v4
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: projects/462797584958/locations/global/workloadIdentityPools/github/providers/github
          service_account: icfp-github@icfp-contest-compute.iam.gserviceaccount.com

      - uses: docker/login-action@v3
        with:
          registry: asia-northeast1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          file: frontend/Dockerfile
          push: true
          tags: asia-northeast1-docker.pkg.dev/icfp-contest-compute/icfpc2024/frontend:latest

      - run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          cat >>~/.ssh/config <<END
          Host icfp.badalloc.com
            User root
            IdentityFile ~/.ssh/id_ed25519
            StrictHostKeyChecking no
          END
        env:
          SSH_KEY: ${{ secrets.PROD_DEPLOY_PRIVATE_KEY }}

      - run: ssh icfp.badalloc.com 'cd /root/icfpc2024 && git pull'
      - run: ssh icfp.badalloc.com 'cd /root/icfpc2024/frontend && docker compose up --detach --force-recreate'
